# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from c2p.framework.api.proto import policy_pb2 as c2p_dot_framework_dot_api_dot_proto_dot_policy__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in c2p/framework/api/proto/policy_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PolicyEngineStub(object):
    """get policy results from PVP
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Generate = channel.unary_unary(
                '/protocols.PolicyEngine/Generate',
                request_serializer=c2p_dot_framework_dot_api_dot_proto_dot_policy__pb2.PolicyRequest.SerializeToString,
                response_deserializer=c2p_dot_framework_dot_api_dot_proto_dot_policy__pb2.GenerateResponse.FromString,
                _registered_method=True)
        self.GetResults = channel.unary_unary(
                '/protocols.PolicyEngine/GetResults',
                request_serializer=c2p_dot_framework_dot_api_dot_proto_dot_policy__pb2.PolicyRequest.SerializeToString,
                response_deserializer=c2p_dot_framework_dot_api_dot_proto_dot_policy__pb2.ResultsResponse.FromString,
                _registered_method=True)


class PolicyEngineServicer(object):
    """get policy results from PVP
    """

    def Generate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PolicyEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Generate': grpc.unary_unary_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=c2p_dot_framework_dot_api_dot_proto_dot_policy__pb2.PolicyRequest.FromString,
                    response_serializer=c2p_dot_framework_dot_api_dot_proto_dot_policy__pb2.GenerateResponse.SerializeToString,
            ),
            'GetResults': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResults,
                    request_deserializer=c2p_dot_framework_dot_api_dot_proto_dot_policy__pb2.PolicyRequest.FromString,
                    response_serializer=c2p_dot_framework_dot_api_dot_proto_dot_policy__pb2.ResultsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protocols.PolicyEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('protocols.PolicyEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PolicyEngine(object):
    """get policy results from PVP
    """

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protocols.PolicyEngine/Generate',
            c2p_dot_framework_dot_api_dot_proto_dot_policy__pb2.PolicyRequest.SerializeToString,
            c2p_dot_framework_dot_api_dot_proto_dot_policy__pb2.GenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protocols.PolicyEngine/GetResults',
            c2p_dot_framework_dot_api_dot_proto_dot_policy__pb2.PolicyRequest.SerializeToString,
            c2p_dot_framework_dot_api_dot_proto_dot_policy__pb2.ResultsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
